### PR TITLE
Bring AppInspect current in Dockerfile

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
@outcoldman please review

**Comment by outcoldman** [comment]
I have seen your PR. Please give me a time to review it. It is not a simple change, considering that you are changing python version to 3, so I am not sure if there are will be some issues with old versions of Splunk.
Any reason why to switch to python 3? Does this version of app inspect only runs on python 3?

**Comment by gliptak** [comment]
@outcoldman I didn't see any notes on AppInspect going ```3.x``` only and ```2.7``` is certainly on its way out

https://www.splunk.com/en_us/blog/platform/admins-and-developers-we-re-transitioning-to-python-3.html

**Comment by outcoldman** [comment]
Is there any issues with keeping it just python 2 for now and just bumping the version? And maybe create a separate pr for switching to python 3?

**Comment by gliptak** [comment]
@outcoldman closing at this time

**Comment by outcoldman** [comment]
@gliptak you were right, seems like it is a requirement for the latest appinspect, see https://dev.splunk.com/enterprise/docs/developapps/testvalidate/appinspect/splunkappinspectclitool/installappinspect/installappinspectonlinux

```
AppInspect CLI requires Python 3.7 during runtime, but you can use it to validate apps developed using Python 2.x as well as Python 3.x.
```

I will work on merging this change. Just will do a few modifications. Thanks!

**Comment by outcoldman** [comment]
@gliptak I have published the change https://github.com/outcoldsolutions/docker-splunk-appinspect/commit/e3d4de9295f91dde5c6e6571784a679de3e07618, and the 2.3.1 image as well.

**Pull request closed without merging**
